sudo: false
language: ruby
cache: bundler
rvm:
  - 2.1
  - 2.2
  - 2.3.0
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
before_script:
  - bundle exec rake db:create db:migrate
branches:
  only:
    - master

addons:
  code_climate:
    repo_token: 8850bccc6911d74965627b1fafe753beb368fab00d33de0c7576c6598fc1220e
