method: :smtp
settings:
  address: <%= ENV['SMTP_SERVER'] %>
  port:    <%= ENV['SMTP_PORT'] %>
  domain:  <%= ENV['DOMAIN'] %>
  authentication:  :login
  user_name: <%= ENV['SMTP_USERNAME'] %>
  password: <%= ENV['SMTP_PASSWORD'] %>
